// Proxy endpoints to store students in Supabase (free tier).
// Requirements: set these environment variables in Vercel (Project Settings → Environment Variables):
// SUPABASE_URL, SUPABASE_KEY
// Create a table `students` in Supabase with columns:
// id (bigint, primary key, generated by default as identity), name (text), cedula (text), email (text), phone (text), year (int), status (text), created_at (timestamp with time zone, default now())

const SUPABASE_URL = (process.env.SUPABASE_URL || '')
  .replace(/\/rest\/v1\/?$/, '')
  .replace(/\/$/, '');
const SUPABASE_KEY = process.env.SUPABASE_KEY;

const requireSupabase = (res) => {
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    res.status(500).json({ error: 'No se ha configurado Supabase en el servidor.' });
    return false;
  }
  return true;
};

const supabaseFetch = async (path, opts = {}) => {
  const url = `${SUPABASE_URL}/rest/v1${path}`;
  const headers = Object.assign({
    apikey: SUPABASE_KEY,
    Authorization: `Bearer ${SUPABASE_KEY}`,
    Accept: 'application/json',
    'Content-Type': 'application/json',
  }, opts.headers || {});

  return fetch(url, Object.assign({}, opts, { headers }));
};

module.exports = async (req, res) => {
  if (!requireSupabase(res)) return;

  try {
    if (req.method === 'GET') {
      const { year } = req.query || {};
      if (!year) {
        const response = await supabaseFetch('/students');
        const data = await response.json();
        return res.status(response.status).json(data);
      }
      const query = `?year=eq.${encodeURIComponent(year)}`;
      const response = await supabaseFetch(`/students${query}`);
      const data = await response.json();
      return res.status(response.status).json(data);
    }

    if (req.method === 'POST') {
      const body = req.body || await new Promise((resolve, reject) => {
        let b = '';
        req.on('data', (c) => b += c);
        req.on('end', () => resolve(JSON.parse(b || '{}')));
        req.on('error', reject);
      });
      const { name, cedula, email, phone, year, BoletaVisible, paymentStatus, paidAmount, payments } = body;
      if (!name || !year) return res.status(400).json({ error: 'Falta nombre o año.' });
      const r = await supabaseFetch('/students', {
        method: 'POST',
        body: JSON.stringify([{ name, cedula: cedula || null, email: email || null, phone: phone || null, year: Number(year), status: '', payment_status: paymentStatus || 'no_pago', paid_amount: Number(paidAmount) || 0, payments: payments || {}, BoletaVisible: BoletaVisible === 'SI' ? 'SI' : 'NO' }]),
        headers: { Prefer: 'return=representation' },
      });
      const data = await r.json();
      if (!r.ok) return res.status(r.status).json({ error: data.message || data.error || 'Supabase rechazó el estudiante.' });
      return res.status(201).json(data[0]);
    }

    if (req.method === 'PATCH' || req.method === 'PUT') {
      const body = req.body || await new Promise((resolve, reject) => {
        let b = '';
        req.on('data', (c) => b += c);
        req.on('end', () => resolve(JSON.parse(b || '{}')));
        req.on('error', reject);
      });
      const { id, name, cedula, email, phone, year, status, BoletaVisible, payments, paymentStatus, paidAmount } = body;
      if (!id) return res.status(400).json({ error: 'Falta id para actualizar.' });
      const changes = { name, cedula, email, phone, year: year === undefined ? undefined : Number(year), status, BoletaVisible, payments, payment_status: paymentStatus, paid_amount: paidAmount === undefined ? undefined : Number(paidAmount) || 0 };
      Object.keys(changes).forEach((key) => changes[key] === undefined && delete changes[key]);
      const r = await supabaseFetch(`/students?id=eq.${encodeURIComponent(id)}`, {
        method: 'PATCH',
        body: JSON.stringify(changes),
        headers: { Prefer: 'return=representation' },
      });
      const data = await r.json();
      if (!r.ok) return res.status(r.status).json({ error: data.message || data.error || 'Supabase rechazó la actualización.' });
      if (!Array.isArray(data) || !data.length) return res.status(404).json({ error: 'Estudiante no encontrado en Supabase.' });
      return res.json(data[0]);
    }

    if (req.method === 'DELETE') {
      const { id } = req.query || {};
      if (!id) return res.status(400).json({ error: 'Falta id para eliminar.' });
      const r = await supabaseFetch(`/students?id=eq.${encodeURIComponent(id)}`, { method: 'DELETE' });
      if (r.status === 204) return res.json({ success: true });
      const data = await r.json();
      return res.json(data);
    }

    res.status(405).json({ error: 'Method not allowed' });
  } catch (error) {
    console.error('students API error:', error);
    res.status(500).json({ error: error.message || String(error) });
  }
};
