create table if not exists public.attendances (
  id bigint generated by default as identity primary key,
  student_id text not null,
  date date not null,
  subject text not null,
  subject_label text,
  status text not null check (status in ('asistente', 'inasistente')),
  created_at timestamptz not null default now(),
  unique (student_id, date, subject)
);

alter table public.attendances enable row level security;

drop policy if exists "allow attendance select" on public.attendances;
create policy "allow attendance select"
on public.attendances for select
to anon, authenticated
using (true);

drop policy if exists "allow attendance insert" on public.attendances;
create policy "allow attendance insert"
on public.attendances for insert
to anon, authenticated
with check (true);

drop policy if exists "allow attendance update" on public.attendances;
create policy "allow attendance update"
on public.attendances for update
to anon, authenticated
using (true)
with check (true);

alter table public.students
add column if not exists "BoletaVisible" text not null default 'NO';

alter table public.students
add column if not exists payments jsonb not null default '{}'::jsonb;

alter table public.students
add column if not exists payment_status text not null default 'no_pago';

alter table public.students
add column if not exists paid_amount numeric not null default 0;

notify pgrst, 'reload schema';

