create table if not exists public.students (
  id text primary key,
  name text not null,
  cedula text,
  email text,
  phone text,
  year integer not null default 1,
  status text not null default '',
  "BoletaVisible" text not null default 'NO',
  payments jsonb not null default '{}'::jsonb,
  payment_status text not null default 'no_pago',
  paid_amount numeric not null default 0,
  attendance jsonb not null default '{}'::jsonb,
  attendance_by_date jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.attendances (
  id bigint generated by default as identity primary key,
  student_id text not null,
  date date not null,
  subject text not null,
  subject_label text,
  status text not null check (status in ('asistente', 'inasistente')),
  created_at timestamptz not null default now(),
  unique (student_id, date, subject)
);

alter table public.students enable row level security;
alter table public.attendances enable row level security;

drop policy if exists "allow students select" on public.students;
create policy "allow students select"
on public.students for select
to anon, authenticated
using (true);

drop policy if exists "allow students insert" on public.students;
create policy "allow students insert"
on public.students for insert
to anon, authenticated
with check (true);

drop policy if exists "allow students update" on public.students;
create policy "allow students update"
on public.students for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "allow students delete" on public.students;
create policy "allow students delete"
on public.students for delete
to anon, authenticated
using (true);

drop policy if exists "allow attendance select" on public.attendances;
create policy "allow attendance select"
on public.attendances for select
to anon, authenticated
using (true);

drop policy if exists "allow attendance insert" on public.attendances;
create policy "allow attendance insert"
on public.attendances for insert
to anon, authenticated
with check (true);

drop policy if exists "allow attendance update" on public.attendances;
create policy "allow attendance update"
on public.attendances for update
to anon, authenticated
using (true)
with check (true);

alter table public.students
add column if not exists "BoletaVisible" text not null default 'NO';

alter table public.students
add column if not exists payments jsonb not null default '{}'::jsonb;

alter table public.students
add column if not exists payment_status text not null default 'no_pago';

alter table public.students
add column if not exists paid_amount numeric not null default 0;

alter table public.students
add column if not exists attendance jsonb not null default '{}'::jsonb;

alter table public.students
add column if not exists attendance_by_date jsonb not null default '{}'::jsonb;

notify pgrst, 'reload schema';

